from django.urls import path

from .views import (
    CampaignDetailView,
    CampaignListCreateView,
    CampaignPauseView,
    CampaignRetryFailedView,
    CampaignResumeView,
    CampaignSendView,
    CampaignStopView,
    ContactImportView,
    ContactPastePreviewView,
    ContactPasteCommitView,
    ContactDeleteAllView,
    ContactDetailView,
    ContactListCreateView,
    DashboardView,
    FailedMessagesView,
    MediaUploadView,
    MediaDownloadView,
    ReportsView,
    WhatsAppConnectView,
    WhatsAppDisconnectView,
    WhatsAppStatusView,
    GroupDetailView,
    GroupListCreateView,
    SettingsView,
)

urlpatterns = [
    path("contacts", ContactListCreateView.as_view(), name="contacts"),
    path("contacts/all", ContactDeleteAllView.as_view(), name="contacts-delete-all"),
    path("contacts/<int:pk>", ContactDetailView.as_view(), name="contact-detail"),
    path("contacts/import", ContactImportView.as_view(), name="contacts-import"),
    path("contacts/paste/preview", ContactPastePreviewView.as_view(), name="contacts-paste-preview"),
    path("contacts/paste/import", ContactPasteCommitView.as_view(), name="contacts-paste-import"),
    path("campaigns", CampaignListCreateView.as_view(), name="campaigns"),
    path("campaigns/<int:pk>", CampaignDetailView.as_view(), name="campaign-detail"),
    path("campaigns/<int:pk>/send", CampaignSendView.as_view(), name="campaign-send"),
    path("campaigns/<int:pk>/pause", CampaignPauseView.as_view(), name="campaign-pause"),
    path("campaigns/<int:pk>/resume", CampaignResumeView.as_view(), name="campaign-resume"),
    path("campaigns/<int:pk>/stop", CampaignStopView.as_view(), name="campaign-stop"),
    path("campaigns/<int:pk>/retry-failed", CampaignRetryFailedView.as_view(), name="campaign-retry-failed"),
    path("media/upload", MediaUploadView.as_view(), name="media-upload"),
    path("media/<int:pk>/download", MediaDownloadView.as_view(), name="media-download"),
    path("reports", ReportsView.as_view(), name="reports"),
    path("dashboard", DashboardView.as_view(), name="dashboard"),
    path("failed-messages", FailedMessagesView.as_view(), name="failed-messages"),
    path("whatsapp/status", WhatsAppStatusView.as_view(), name="whatsapp-status"),
    path("whatsapp/connect", WhatsAppConnectView.as_view(), name="whatsapp-connect"),
    path("whatsapp/disconnect", WhatsAppDisconnectView.as_view(), name="whatsapp-disconnect"),
    path("groups", GroupListCreateView.as_view(), name="groups"),
    path("groups/<int:pk>", GroupDetailView.as_view(), name="group-detail"),
    path("settings", SettingsView.as_view(), name="settings"),
]
